# Assignment day 3 

### Question 1
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [ ]:
#numpy.arange([start, ]stop, [step, ]dtype=None)

In [2]:
import numpy as np
arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

### Question 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
lst1 = []
lst2 = []

print('Enter Numbers:')
for i in range(1,6):
    item = int(input())
    lst1.append(item)
print('Enter second lists element')

for i in range(1,6):
    item = int(input())
    lst2.append(item)

print(lst1)
arr1 = np.array(lst1)
arr2 = np.array(lst2)
print(arr1)
print(arr2)

print(arr1 + arr2)

Enter Numbers:
5
7
8
6
2
Enter second lists element
1
5
7
8
9
[5, 7, 8, 6, 2]
[5 7 8 6 2]
[1 5 7 8 9]
[ 6 12 15 14 11]


### Question 3
Write a code snippet to find the dimensions of a ndarray and its size.


In [10]:
arr = np.array([[4,5,6],[7,8,9],[11,12,13]])
print(arr.dtype)
print(arr.size)
print(arr.shape)#m x n matix
print(arr.ndim) #to find dimention

int32
9
(3, 3)
2


## Question 4
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [12]:
a_1d_array = np.array([1,2,3,4])
a_2d_array = np.reshape((a_1d_array),(-1,2))

print(a_2d_array)

[[1 2]
 [3 4]]


### Question 5
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [13]:
arr = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[2,3]])
print(arr)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [2 3]]


In [14]:
print('Horizontal Append:', np.hstack((arr, arr2)))

Horizontal Append: [[1 2 5 6]
 [3 4 2 3]]


In [15]:
print('Horizontal Append:', np.vstack((arr, arr2)))

Horizontal Append: [[1 2]
 [3 4]
 [5 6]
 [2 3]]


### Question 6
How to get unique items and counts of unique items?

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr[0][1]

2

In [19]:
arr[0][2]

3